model:
  n_input_features: 512
  n_units: 768
  rnn_dropout: 0.4
  rnn_trainable: true
  n_layers: 5
  patch_size: 14
  patch_stride: 4
  input_network:
    n_input_layers: 1
    input_layer_sizes:
      - 512
    input_trainable: true
    input_layer_dropout: 0.2

gpu_number: '-1'
mode: train
use_amp: false
output_dir: trained_models/temporal_masked_model
checkpoint_dir: trained_models/temporal_masked_model/checkpoint

init_from_checkpoint: true
init_checkpoint_path: ../data/t15_pretrained_rnn_baseline/checkpoint/best_checkpoint

save_best_checkpoint: true
save_all_val_steps: false
save_final_model: true
save_val_metrics: true
early_stopping: true
early_stopping_val_steps: 15

num_training_batches: 3000
batches_per_val_step: 200
batches_per_train_log: 50

lr_scheduler_type: cosine
lr_max: 0.0005
lr_min: 0.00001
lr_decay_steps: 3000
lr_warmup_steps: 150

lr_max_day: 0.0005
lr_min_day: 0.00001
lr_decay_steps_day: 3000
lr_warmup_steps_day: 150

beta0: 0.9
beta1: 0.999
epsilon: 0.1
weight_decay: 0.001
weight_decay_day: 0
seed: 10
grad_norm_clip_value: 10

log_individual_day_val_PER: true
log_val_skip_logs: false
save_val_logits: false
save_val_data: false

dataset:
  data_transforms:
    white_noise_std: 1.2
    constant_offset_std: 0.25
    random_walk_std: 0.0
    random_walk_axis: -1
    static_gain_std: 0.0
    random_cut: 3
    smooth_kernel_size: 100
    smooth_data: true
    smooth_kernel_std: 2
    temporal_mask_enabled: true
    temporal_mask_prob: 0.25
    temporal_mask_length: 6
  
  neural_dim: 512
  batch_size: 32
  n_classes: 41
  max_seq_elements: 500
  days_per_batch: 3
  seed: 1
  num_dataloader_workers: 2
  loader_shuffle: true
  must_include_days: null
  test_percentage: 0.1
  feature_subset: null
  dataset_dir: ../data/hdf5_data_final
  bad_trials_dict: null
  
  sessions:
    - t15.2023.08.11
    - t15.2023.08.13
    - t15.2023.08.18
    - t15.2023.08.20
    - t15.2023.08.25
    - t15.2023.08.27
    - t15.2023.09.01
    - t15.2023.09.03
    - t15.2023.09.24
    - t15.2023.09.29
    - t15.2023.10.01
    - t15.2023.10.06
    - t15.2023.10.08
    - t15.2023.10.13
    - t15.2023.10.15
    - t15.2023.10.20
    - t15.2023.10.22
    - t15.2023.11.03
    - t15.2023.11.04
    - t15.2023.11.17
    - t15.2023.11.19
    - t15.2023.11.26
    - t15.2023.12.03
    - t15.2023.12.08
    - t15.2023.12.10
    - t15.2023.12.17
    - t15.2023.12.29
    - t15.2024.02.25
    - t15.2024.03.03
    - t15.2024.03.08
    - t15.2024.03.15
    - t15.2024.03.17
    - t15.2024.04.25
    - t15.2024.04.28
    - t15.2024.05.10
    - t15.2024.06.14
    - t15.2024.07.19
    - t15.2024.07.21
    - t15.2024.07.28
    - t15.2025.01.10
    - t15.2025.01.12
    - t15.2025.03.14
    - t15.2025.03.16
    - t15.2025.03.30
    - t15.2025.04.13
  
  dataset_probability_val:
    - 0
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 0
    - 1
    - 1
    - 1
    - 0
    - 0
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1